name: Etude Download Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Download latest release
      run: |
        echo $(gh release view --json tagName --jq '.tagName')
        LATEST_RELEASE_TAG=$(gh release view --json tagName --jq '.tagName')
        echo $LATEST_RELEASE_TAG
        echo $(gh release view $LATEST_RELEASE_TAG --json assets --jq '.assets')
        ASSET_DOWNLOAD_URL=$(gh release view $LATEST_RELEASE_TAG --json assets --jq '.assets[0].url')
        echo $ASSET_DOWNLOAD_URL
        wget $ASSET_DOWNLOAD_URL || true

    - name: ls
      run: ls -lt